### ISSUE TITLE
Clarify input files for scripts with dependencies

### ISSUE THREAD

**Issue by justinfagnani** [google/wireit#121]
In this section: https://github.com/google/wireit#input-and-output-files

It reads like I would need to specify all the inputs of a bundle script, including the files it reads. But the `bundle` script example only includes the _config_ as an input. I guess that the outputs of its dependencies are automatically used as inputs, but without seeing that example this isn't how I would have tried to write a bundle script myself.

**Comment by aomarks** [comment]
The way it actually works is this:

1. When we run a script, we generate a *fingerprint*. The fingerprint is comprised of the configuration of the script, plus the hashes of the input files, **plus the fingerprints of the dependencies**.

3. If the `.wireit/fingerprint` file matches the latest fingerprint, the script is fresh and we do nothing. If there is a `.wireit/cache/<script>/<fingerprint>` entry, then we restore those files. Failing those, we run the script.

So if A depends on B, the `output` of B does not actually directly affect the fingerprint of `A`. Only the *input files* of B do, because B's fingerprint is included in A's fingerprint. 

This approach is somewhat conservative, meaning we err on the side of running rather than skipping. It means we do not need to assume that B has correctly declared its outputs in order to decide whether A should run. We instead just assume that if something changed that caused B to re-run, then A should re-run too, regardless of what outputs were produced.

See also https://github.com/google/wireit/issues/245 where we are discussing changing this approach to be a little less conservative, and perhaps more intuitive too.

Closing this issue.
