### ISSUE TITLE
Question: best practices in regards to caching in a monorepo

### ISSUE THREAD

**Issue by jonkoops** [google/wireit#1245]
Hi, I have a question in regards to the best practices for caching in a mono-repo (in my case using PNPM). In order to prevent cache hits from happening when dependencies have changed, should I be providing my lockfile and local `package.json` to the `files` field? For example, given the following structure:

```
├─ a/
│  ├─ src/
│  ├─ package.json
├─ package.json
├─ pnpm-workspace.yaml
├─ pnpm-lock.yaml
```

Should `files` be specified as follows (abbreviated)?

**a/package.json**
```json
{
  "files": [
    "src",
    "package.json",
    "../pnpm-lock.yaml"
  ]
}
```

Or can WireIt automatically detect that the dependencies have changed and can I omit anything after `src`?

**Comment by augustjk** [comment]
wireit auto-includes lockfiles as part of the fingerprint, including those in parent directories, so you don't need to include those in `"files"`. see https://github.com/google/wireit?tab=readme-ov-file#package-locks

`package.json` also doesn't need to be added to `"files"` as versions there don't reflect wha's actually installed since they only contain semver ranges. the `package.json` will already be parsed for analyzing the script and dependencies, so any relevant changes there will be picked up.

**Comment by jonkoops** [comment]
Perfect, I  missed this when reading the documentation, thanks for answering my question!
