### ISSUE TITLE
Cached output files inside .wireit should be used by default if build artefacts are not present 

### ISSUE THREAD

**Issue by yuriteixeira** [google/wireit#205]
I just read #150 and discovered that [I had to manually `rm -rf .wireit/*/state` in order to use the local cache whenever the outputs are not present](https://github.com/google/wireit/issues/150#issuecomment-1111751788) (eg: in a private CI environment, where I'm manually restoring the cache from a previous build), and that seemed very counter-intuitive. 

I was ready to start working a PR to fix "the issue" since for me, not having this by default looked like a bug, especially when the documentation doesn't seem to make this caveat clear.

**Comment by aomarks** [comment]
Interesting use case, thanks for the report!

So I assume you are caching a `.wireit` directory, but not the output files that go with it? Wireit then reads the `state` file, and thinks that the output is already present.

We could potentially check for output files as you suggest, and assume that if there are no matching files, that the `state` file must be out-of-sync. This wouldn't work in the case where you _changed_ your output files, or only deleted _some_ of them, though. I suppose we could store a manifest of _all_ output files and their content hashes along with the `state` file, and then validate that everything is as expected before assuming that the current `state` is fresh. This does add extra cost to every script invocation, though (potentially significant if there are a large number of output files).

Can I ask what you're using for CI and your caching layer, and what key you are using for the cache entry?

The GitHub Actions caching integration we have doesn't suffer from this problem, because it manages cache entries at a very granular level.

**Comment by aomarks** [comment]
> Correct. We store build artifacts when building the `main` branch and reuse it in every build.

A slight variation of your workaround could be to only cache `.wireit/cache`, so that you don't have to `rm .wireit/state`.

**Comment by aomarks** [comment]
Another idea that could work for your CI use-case, and which doesn't require any checking of output files, would be to store some additional information in the `state` files which would let us detect when we are probably running on a separate machine, which could indicate that the `state` file is out of sync. For example, on GitHub Actions, the combination of `GITHUB_RUN_ID` and `GITHUB_RUN_ID` environment variables could serve this role.

**Comment by aomarks** [comment]
@yuriteixeira Wireit 0.6.1 was just released, which adds output file verification (https://github.com/google/wireit/pull/300). This should mean that you no longer need the workaround discussed here, because Wireit will automatically detect that the output files are out of date and re-run the script.
