### ISSUE TITLE
Support for Yarn Berry

### ISSUE THREAD

**Issue by appsforartists** [google/wireit#286]
I have a bunch of related projects.  Each has a structure like this:

```
packages/core
packages/preact
packages/...
```

where one package provides the framework-agnostic functionality, and sibling packages provide additional features for a particular framework.

Inspired by wireit, I'm exploring merging them into a monorepo with this structure:

```
project-a/packages/core
project-a/packages/preact
project-a/packages/...
project-b/packages/core
project-c/packages/preact
project-c/packages/...
```

To do that, I need to upgrade to Yarn Berry. In Berry, `"build": "wireit"` will only resolve in the current package.json.  To use `devDependencies` shared with sibling packages, [one must use `yarn run -T wireit`](https://yarnpkg.com/cli/run).  This causes the "you must use `wireit` naked" error to be thrown.

Would you be amenable to a PR that amends this line:
https://github.com/google/wireit/blob/48839ed5da4de5e0df59f6e9931a61d6efb9503b/src/analyzer.ts#L338

to instead check
```ts
[`wireit`, `yarn run -T wireit`].includes(scriptCommand.value)
```

This will provide the same safety (that wireit isn't being chained into a larger command), but will allow a single wireit installation to be shared across sibling packages in modern versions of yarn.

**Comment by aomarks** [comment]
Interesting that Yarn is introducing more incompatibility with npm...

Would another solution (maybe more correct from Yarn's perspective?) be to make wireit a dependency of all your packages, instead of just the top one?

**Comment by appsforartists** [comment]
I'm sure you could include it in every package.  It just introduces an annoying amount of maintenance (and duplicative consumption on disk).  I can also imagine subtle potential problems if the versions of `wireit` used in a project deviate (and thus behave differently).

Yet another option would be a `--chill`/`--force`/`--i-know-what-im-doing` flag that suppresses the error.

I don't know of other tools that are so stubborn about how they are called.  I don't know how beneficial it is (e.g. how many people would have done bad things that have been caught by the assertion), but it has been a frustrating hurdle to workaround.

**Comment by appsforartists** [comment]
Another potential option would be allowing `wireit` to accept which target to build as a command line flag.  This is also potentially cumbersome (because you'd have to type the path to the target you're already in), but avoids the multiple drifting installations problem:

e.g.
```
project-a/packages/core > yarn run -T wireit project-a/core:build 
```

Presently, this fails with
```
❌ wireit must be launched with "npm run" or a compatible command.
```

**Comment by aomarks** [comment]
For background, the reason we are strict about `script` being `wireit` is to prevent this scenario:

```json
{
  "scripts": {
    "foo": "bad-command-i-forgot-to-update-to-wireit",
    "bar": "wireit"
  },
  "wireit": {
    "foo": {
      "command": "correct-command"
    },
    "bar": {
      "dependencies": [
        "foo"
      ]
    }
  }
}
```

We want to be sure that [1] `npm run foo` and [2] `npm run bar` both end up running `correct-command`. But if we didn't check the script value, then [1] would run the bad command, while [2] would run the correct command. That's a footgun that might lead to some confusing situations, so we want to help the user avoid it by being strict about checking that the script is correctly delegating to wireit.

Given this is how Yarn 2.x works, I guess it seems reasonable change the check to `scriptCommand.value === 'wireit' || scriptCommand.value === 'yarn run -T wireit'`. Seems like we should maybe actually enforce `yarn run -T -B wireit`, because it sounds like otherwise you could define a local `wireit` script that would take precedence?

It would be nice if we could test this. Is it possible to have both versions of Yarn installed at the same time?

**Comment by appsforartists** [comment]
Thanks for the context!

You can programmatically toggle between yarn versions:

https://yarnpkg.com/cli/set/version

presumably you could run your tests with `yarn@1`, and then run `yarn use version berry` and run the relevant tests again (or vice-versa, swapping `classic` for `berry`).
