### ISSUE TITLE
Compare GNU Parallel to WireIt's main usage

### ISSUE THREAD

**Issue by danny-huang-openfind** [google/wireit#566]
Notice: this is not a feature request or an error respond on using wireit, just a question which I'm curious about.
If this issue violate any rule of this project, please directly close this issue.

GNU Parallel's wikipedia page:
https://zh.wikipedia.org/wiki/GNU_parallel

Since the main usage of wireit looks as same as this tool, I'm wondering if there is any difference between these two.
Or this may be my misunderstood of both wireit and GNU parallel's usage, in that case, may I ask for a explanation of these two tools?

**Comment by aomarks** [comment]
Hi @danny-huang-openfind, thanks for the question.

#### Similarities:
- Both execute shell commands
- Both can run multiple shell commands in parallel

#### Differences:
- Wireit is tied to the [npm](https://en.wikipedia.org/wiki/Npm_(software)) ecosystem. It has to be launched using an npm-script runner like npm, pnpm, or yarn. GNU parallel is a more general-purpose unix command that you invoke directly from the command-line.

- Wireit scripts are configured in the `scripts` section of a `package.json` file, while GNU parallel scripts are provided directly as command-line arguments.

- Wireit is significantly more powerful than GNU parallel, with the following additional features:
  - Wireit scripts are connected into a *graph* using [dependencies](https://github.com/google/wireit#dependencies). So if you say "A depends on B and C" then B and C will first run in [parallel](https://github.com/google/wireit#parallelism), followed by A running only when both B and C are done. GNU parallel runs all commands in parallel, since it has no notion of a dependency graph.
  - Wireit has a built-in [*watch*](https://github.com/google/wireit#watch-mode) mode, where scripts will automatically re-execute whenever their input files change.
  - Wireit won't run scripts that have recently run and [don't need to run again](https://github.com/google/wireit#incremental-build).
  - Wireit can restore output from a [*cache*](https://github.com/google/wireit#caching) (either from local disk, or on GitHub Actions).
  - Wireit has the concept of [*services*](https://github.com/google/wireit#services), where a process like a server can be brought up and shut down automatically
